antlr:
	java -classpath /usr/local/lib/antlr-4.0-complete.jar org.antlr.v4.Tool -o ./ -listener -no-visitor -package com.metadave.knowsql.parser ./src/main/java/com/metadave/knowsql/parser/KnowSQL.g4
